name: Publish to GitHub Packages

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    uses: cboone/gh-actions/.github/workflows/publish-to-npm.yml@844bf31d4ec26df9d0aa531e79d8c3fccf9f0638 # v3.1.0
    with:
      node-version: "20"
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
